language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=">=1.8,<2.0" OSCAR_VERSION=">=1.3,<1.6"
  - DJANGO_VERSION=">=1.8,<2.0" OSCAR_VERSION=">=1.3,<1.6"
install:
  - pip install Django$DJANGO_VERSION django-oscar$OSCAR_VERSION
  - pip install .
  - pip install -r requirements.txt
script:
  - py.test --pep8 --cov oscar_support
after_success:
  - coveralls
