language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION=">=1.5,<1.6"
install:
  - pip install Django$DJANGO_VERSION
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - npm -g install less@1.3.3 phantomjs
script:
  - py.test --pep8 --cov oscar_support
after_success:
  - coveralls
